name: Pull Request Check

on: pull_request

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: "SateSate"
          java-version: 17
          cache: "gradle"
      - name: Run unit Test
        run: ./gradlew testDebugUnitTest
